# Generated by Django 4.2.4 on 2023-08-31 08:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('username', models.CharField(unique=True)),
                ('password', models.TextField()),
                ('employee_type', models.CharField(choices=[('E', 'Employee'), ('M', 'Manager'), ('B', 'BHR'), ('BU', 'BUHR')], default='E', max_length=2)),
                ('email_id', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=12, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resignation',
            fields=[
                ('resignation_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_designation', models.CharField(choices=[('FC', 'FTC'), ('Pb', 'Probationer'), ('L6', 'L6-L5-L4'), ('L5', 'L6-L5-L4'), ('L4', 'L6-L5-L4'), ('L3', 'L3-L2-L1'), ('L2', 'L3-L2-L1'), ('L1', 'L3-L2-L1')], default='FC', max_length=2, null=True)),
                ('resignation_date', models.DateField(null=True)),
                ('actual_resignation_date', models.DateField(null=True)),
                ('notice_period_days', models.IntegerField(null=True)),
                ('notice_period_shortfall_days', models.IntegerField(null=True)),
                ('notice_period_recovery', models.PositiveIntegerField(null=True)),
                ('resignation_reason', models.TextField(null=True, validators=[django.core.validators.MinLengthValidator(300)])),
                ('manager_approval', models.BooleanField(default=False, null=True)),
                ('manager_reason', models.TextField(null=True, validators=[django.core.validators.MinLengthValidator(300)])),
                ('manager_remark', models.TextField(blank=True, validators=[django.core.validators.MinLengthValidator(100)])),
                ('bhr_approval', models.BooleanField(default=False, null=True)),
                ('bhr_reason', models.TextField(null=True, validators=[django.core.validators.MinLengthValidator(300)])),
                ('bhr_remark', models.TextField(null=True, validators=[django.core.validators.MinLengthValidator(100)])),
                ('bhur_approval', models.BooleanField(default=False, null=True)),
                ('bhur_reason', models.TextField(null=True, validators=[django.core.validators.MinLengthValidator(300)])),
                ('bhur_remark', models.TextField(null=True, validators=[django.core.validators.MinLengthValidator(100)])),
                ('lwd_final', models.DateField(null=True)),
                ('deleted', models.BooleanField(default=False, editable=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('employee_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='esep.registration')),
            ],
        ),
    ]
