# Generated by Django 4.2.4 on 2023-08-31 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esep', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resignation',
            name='resignation_current_status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
