# Generated by Django 4.2.4 on 2023-08-31 13:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esep', '0002_resignation_resignation_current_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resignation',
            name='manager_remark',
            field=models.TextField(null=True, validators=[django.core.validators.MinLengthValidator(100)]),
        ),
    ]
