# Generated by Django 4.2.4 on 2023-09-04 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esep', '0004_resignation_esp_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='resignation',
            name='first_name',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='resignation',
            name='last_name',
            field=models.CharField(null=True),
        ),
    ]
